{% set name = "awscrt" %}
{% set version = "0.27.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cb23cb767ca2e3c0007c899b289d668d28aeb055534df35a741847135f6cd91c
  patches:
    - patches/0001-Don-t-force-static-linkage.patch

build:
  number: 0
  skip: true  # [py<38]
  # It is in requirements: https://github.com/awslabs/aws-crt-python/blob/v0.27.4/setup.py#L220-L230
  ignore_run_exports:
    - aws-c-sdkutils
    - aws-c-compression

requirements:
  build:
    - {{ compiler('c') }}
    - patch  # [not win]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - setuptools >=75.3.1
    - wheel >=0.45.1
    - s2n 1.5.14  # [linux]
    - aws-c-common 0.12.3
    - aws-c-sdkutils 0.2.4
    - aws-c-cal 0.9.2
    - aws-c-io 0.20.1
    - aws-checksums 0.2.7
    - aws-c-compression 0.3.1
    - aws-c-event-stream 0.5.5
    - aws-c-http 0.10.2
    - aws-c-auth 0.9.0
    - aws-c-mqtt 0.13.2
    - aws-c-s3 0.8.3
  run:
    - python

# test/test_crypto.py::TestCredentials::test_ed25519_keygen

test:
  source_files:
    - test
  imports:
    - awscrt
    - awscrt.eventstream
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v test
  requires:
    - pytest
    - pip
    - websockets

about:
  home: https://github.com/awslabs/aws-crt-python
  summary: A common runtime for AWS Python projects
  description: Python 3 bindings for the AWS Common Runtime.
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  doc_url: https://awslabs.github.io/aws-crt-python
  dev_url: https://github.com/awslabs/aws-crt-python

extra:
  recipe-maintainers:
    - ocefpaf
    - xhochy