{% set version = "0.23.8" %}

package:
  name: awscrt
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/awscrt/awscrt-{{ version }}.tar.gz
  sha256: cba55f3ee80ea3192a0a24e84caad778570250800a59d29ef9efbcd4d1612f2f
  patches:
    - patches/0001-Don-t-force-static-linkage.patch
    - patches/0002_add_aws_auth_header.patch

build:
  number: 0

requirements:
  build:
    - python
    - {{ compiler('c') }}
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - setuptools
    - wheel
    - s2n  # [linux]
    - aws-c-common
    - aws-c-sdkutils
    - aws-c-cal
    - aws-c-io
    - aws-checksums
    - aws-c-compression
    - aws-c-event-stream
    - aws-c-http
    - aws-c-auth
    - aws-c-mqtt
    - aws-c-s3
  run:
    - python

test:
  imports:
    - awscrt
    - awscrt.eventstream
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/awslabs/aws-crt-python
  summary: A common runtime for AWS Python projects
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
    - xhochy