{% set version = "0.23.8" %}

package:
  name: awscrt
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/awscrt/awscrt-{{ version }}.tar.gz
  sha256: cba55f3ee80ea3192a0a24e84caad778570250800a59d29ef9efbcd4d1612f2f
  patches:
    - patches/0001-Don-t-force-static-linkage.patch

build:
  number: 0

requirements:
  build:
    - python
    - {{ compiler('c') }}
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - setuptools
    - wheel
    - s2n  # [linux]
    - aws-c-common 0.11.1
    - aws-c-sdkutils 0.2.3
    - aws-c-cal 0.8.5
    - aws-c-io 0.17.0
    - aws-checksums 0.2.3
    - aws-c-compression 0.3.1
    - aws-c-event-stream 0.5.4
    - aws-c-http 0.9.3
    - aws-c-auth 0.8.5
    - aws-c-mqtt 0.12.2
    - aws-c-s3 0.7.11
  run:
    - python

test:
  imports:
    - awscrt
    - awscrt.eventstream
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/awslabs/aws-crt-python
  summary: A common runtime for AWS Python projects
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
    - xhochy