{% set name = "awscrt" %}
{% set version = "0.37.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9e2ddadc609084b5f60affb8b87e77304fed64e271e2b2b7558186cf65d81e5a
  patches:
    - patches/0001-disable-osx-failing-tests.patch  # [osx]
    - patches/0002-disable-win-failing-test.patch  # [win]
    # Some tests expect status code 404 from httpbin.org, but server returns 503 in Anaconda environment.
    - patches/0003-Disable-404-status-code-tests.patch
    # Increase timeout for test_h2_client to 160 seconds to avoid timeout errors.
    - patches/0004-Increase-timeout-for-test-h2-client.patch

build:
  number: 0
  skip: true  # [py<38]
  script_env:
    # Unvendor AWS libs
    - AWS_CRT_BUILD_USE_SYSTEM_LIBS=1
    - AWS_CRT_BUILD_USE_SYSTEM_LIBCRYPTO=1
    # Cannot enable ed25519 with the current version of aws-c-cal 1.0.0
    # This feature is currently experimental: https://github.com/awslabs/aws-c-cal/blob/v1.0.0/CMakeLists.txt#L29
    # ed25519 tests are disabled using patch on OSX and WIN 
    # - AWS_CRT_BUILD_DISABLE_LIBCRYPTO_USE_FOR_ED25519_EVERYWHERE=1

  # These are also in requirements: https://github.com/awslabs/aws-crt-python/blob/v0.37.0/setup.py#L310
  ignore_run_exports:
    - aws-c-sdkutils
    - aws-c-compression
    - openssl

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools >=75.3.1
    - s2n {{ s2n }}  # [not win]
    - openssl {{ openssl }}  # [not linux]
    - aws-c-common 1.0.1
    - aws-c-sdkutils 1.0.0
    - aws-c-cal 1.0.0
    - aws-c-io 1.0.0
    - aws-checksums 1.0.0
    - aws-c-compression 1.0.0
    - aws-c-event-stream 1.0.0
    - aws-c-http 1.0.0
    - aws-c-auth 1.0.0
    - aws-c-mqtt 1.0.0
    - aws-c-s3 1.2.0
  run:
    - python

test:
  source_files:
    - test
  imports:
    - awscrt
    - awscrt.auth
    - awscrt.cbor
    - awscrt.common
    - awscrt.crypto
    - awscrt.eventstream
    - awscrt.eventstream.rpc
    - awscrt.exceptions
    - awscrt.http
    - awscrt.io
    - awscrt.mqtt
    - awscrt.mqtt_request_response
    - awscrt.mqtt5
    - awscrt.s3
    - awscrt.websocket
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - python -m unittest discover -s test -v
  requires:
    - pip
    - pytest
    - websockets >=15.0.1

about:
  home: https://github.com/awslabs/aws-crt-python
  summary: A common runtime for AWS Python projects
  description: Python 3 bindings for the AWS Common Runtime.
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  doc_url: https://awslabs.github.io/aws-crt-python
  dev_url: https://github.com/awslabs/aws-crt-python

extra:
  recipe-maintainers:
    - ocefpaf
    - xhochy